import { FamilyInterestId } from './interest/FamilyInterest';
import { FamilyMemberId } from './member/FamilyMember';
import type { FamilyMember } from './member/FamilyMember';

export const familyMembersById: Record<FamilyMemberId, FamilyMember> = {
  [FamilyMemberId.Andrew]: {
    id: FamilyMemberId.Andrew,
    firstName: 'Andrew',
    middleName: 'Steven',
    lastName: 'Holbrook',
    nickName: 'Holz',
    role: 'Chaos Wrangler',
    emoji: '🥏',
    bio: 'Creative thinking, software engineer, hobby enthusiast, and dedicated father who loves building things and spending time with family.',
    interests: [
      FamilyInterestId.BoardGames,
      FamilyInterestId.DiscGolf,
      FamilyInterestId.Reading,
      FamilyInterestId.Hiking,
      FamilyInterestId.VideoGames,
      FamilyInterestId.Biking,
      FamilyInterestId.Organizing,
      FamilyInterestId.Coding,
    ],
    order: 1,
  },
  [FamilyMemberId.Brooke]: {
    id: FamilyMemberId.Brooke,
    firstName: 'Brooke',
    middleName: 'Durfee',
    lastName: 'Holbrook',
    role: 'Nurturer',
    emoji: '🏃‍♀️',
    bio: 'Selfless, loving, and always there for her family. Either reading a book or doing something for someone else without complaint. She holds the family together with her love and support.',
    interests: [
      FamilyInterestId.Reading,
      FamilyInterestId.Teaching,
      FamilyInterestId.Yoga,
      FamilyInterestId.Gardening,
      FamilyInterestId.Cooking,
      FamilyInterestId.Hiking,
      FamilyInterestId.Photography,
    ],
    order: 2,
  },
  [FamilyMemberId.Oakley]: {
    id: FamilyMemberId.Oakley,
    firstName: 'Oakley',
    middleName: 'Amelia',
    lastName: 'Holbrook',
    role: 'Creative Explorer',
    emoji: '🐨',
    bio: 'The ambition of a Slytherin, the courage of a Gryffindor, the analytical mind of a Ravenclaw, and the determination of a Hufflepuff. Oakley is a creative and adventurous spirit who is always looking for new things to do.',
    interests: [
      FamilyInterestId.ContentCreation,
      FamilyInterestId.Music,
      FamilyInterestId.Science,
      FamilyInterestId.Soccer,
      FamilyInterestId.Tumbling,
      FamilyInterestId.Hiking,
      FamilyInterestId.Baking,
    ],
    order: 3,
  },
  [FamilyMemberId.Finn]: {
    id: FamilyMemberId.Finn,
    firstName: 'Finn',
    middleName: 'Wolfgang',
    lastName: 'Holbrook',
    role: 'Wise Old Man',
    emoji: '🐺',
    bio: "His gut was busted as a baby, and now he's busting all our guts with laughter. His kind and creative spirit shines through in everything he does, from his funny observations to his excitable discoveries.",
    interests: [
      FamilyInterestId.Minecraft,
      FamilyInterestId.Cooking,
      FamilyInterestId.Reading,
      FamilyInterestId.Hiking,
      FamilyInterestId.Baking,
    ],
    order: 4,
  },
  [FamilyMemberId.Leo]: {
    id: FamilyMemberId.Leo,
    firstName: 'Leo',
    middleName: 'Arthur (Turtle)',
    lastName: 'Holbrook',
    role: 'Playful and Focused',
    emoji: '🐢',
    bio: 'This dude is a thinker and a mover. He is always on the go and has a lot of energy. His thoughtful and logical nature is balanced by his playful and sweet personality, though he can get easily distracted by his own curiosity.',
    interests: [
      FamilyInterestId.Minecraft,
      FamilyInterestId.PlayingOutside,
      FamilyInterestId.Reading,
      FamilyInterestId.VideoGames,
      FamilyInterestId.WobblyLife,
    ],
    order: 5,
  },
  [FamilyMemberId.Wren]: {
    id: FamilyMemberId.Wren,
    firstName: 'Wren',
    middleName: 'Aria',
    lastName: 'Holbrook',
    nickName: 'Wrenny',
    role: 'Energetic and Confident',
    emoji: '🐦',
    bio: 'Just what the family needed. A little spunk, a little daring, and a lot of energy. Her independent and adventurous spirit is matched by her prideful and curious nature, making her a force to be reckoned with.',
    interests: [
      FamilyInterestId.PlayingOutside,
      FamilyInterestId.Legos,
      FamilyInterestId.Music,
      FamilyInterestId.Tumbling,
      FamilyInterestId.Hiking,
    ],
    order: 6,
  },
};
