import { FamilyInterestId, type FamilyInterest } from '.';

export const familyInterestsById: Record<FamilyInterestId, FamilyInterest> = {
  [FamilyInterestId.Baking]: {
    id: FamilyInterestId.Baking,
    name: 'Baking',
    emoji: '🍪',
    color: 'bg-orange-100 text-orange-800',
  },
  [FamilyInterestId.Biking]: {
    id: FamilyInterestId.Biking,
    name: 'Biking',
    emoji: '🚲',
    color: 'bg-sky-100 text-sky-800',
  },
  [FamilyInterestId.BoardGames]: {
    id: FamilyInterestId.BoardGames,
    name: 'Board Games',
    emoji: '🎲',
    color: 'bg-rose-100 text-rose-800',
  },
  [FamilyInterestId.Coding]: {
    id: FamilyInterestId.Coding,
    name: 'Coding',
    emoji: '💻',
    color: 'bg-indigo-100 text-indigo-800',
  },
  [FamilyInterestId.ContentCreation]: {
    id: FamilyInterestId.ContentCreation,
    name: 'Content Creation',
    emoji: '📱',
    color: 'bg-teal-100 text-teal-800',
  },
  [FamilyInterestId.Cooking]: {
    id: FamilyInterestId.Cooking,
    name: 'Cooking',
    emoji: '🍳',
    color: 'bg-red-100 text-red-800',
  },
  [FamilyInterestId.DiscGolf]: {
    id: FamilyInterestId.DiscGolf,
    name: 'Disc Golf',
    emoji: '🥏',
    color: 'bg-lime-100 text-lime-800',
  },
  [FamilyInterestId.Gardening]: {
    id: FamilyInterestId.Gardening,
    name: 'Gardening',
    emoji: '🌱',
    color: 'bg-green-100 text-green-800',
  },
  [FamilyInterestId.Hiking]: {
    id: FamilyInterestId.Hiking,
    name: 'Hiking',
    emoji: '🏃',
    color: 'bg-amber-100 text-amber-800',
  },
  [FamilyInterestId.Legos]: {
    id: FamilyInterestId.Legos,
    name: 'Legos',
    emoji: '🧩',
    color: 'bg-yellow-100 text-yellow-800',
  },
  [FamilyInterestId.Minecraft]: {
    id: FamilyInterestId.Minecraft,
    name: 'Minecraft',
    emoji: '⛏️',
    color: 'bg-emerald-100 text-emerald-800',
  },
  [FamilyInterestId.Music]: {
    id: FamilyInterestId.Music,
    name: 'Music',
    emoji: '🎵',
    color: 'bg-fuchsia-100 text-fuchsia-800',
  },
  [FamilyInterestId.Organizing]: {
    id: FamilyInterestId.Organizing,
    name: 'Organizing',
    emoji: '📦',
    color: 'bg-slate-100 text-slate-800',
  },
  [FamilyInterestId.Photography]: {
    id: FamilyInterestId.Photography,
    name: 'Photography',
    emoji: '📸',
    color: 'bg-zinc-100 text-zinc-800',
  },
  [FamilyInterestId.PlayingOutside]: {
    id: FamilyInterestId.PlayingOutside,
    name: 'Playing Outside',
    emoji: '🌳',
    color: 'bg-green-100 text-green-800',
  },
  [FamilyInterestId.Puzzles]: {
    id: FamilyInterestId.Puzzles,
    name: 'Puzzles',
    emoji: '🧩',
    color: 'bg-blue-100 text-blue-800',
  },
  [FamilyInterestId.Reading]: {
    id: FamilyInterestId.Reading,
    name: 'Reading',
    emoji: '📚',
    color: 'bg-purple-100 text-purple-800',
  },
  [FamilyInterestId.Science]: {
    id: FamilyInterestId.Science,
    name: 'Science',
    emoji: '🔬',
    color: 'bg-cyan-100 text-cyan-800',
  },
  [FamilyInterestId.Soccer]: {
    id: FamilyInterestId.Soccer,
    name: 'Soccer',
    emoji: '⚽',
    color: 'bg-green-100 text-green-800',
  },
  [FamilyInterestId.Swimming]: {
    id: FamilyInterestId.Swimming,
    name: 'Swimming',
    emoji: '🏊',
    color: 'bg-blue-100 text-blue-800',
  },
  [FamilyInterestId.Teaching]: {
    id: FamilyInterestId.Teaching,
    name: 'Teaching',
    emoji: '👨‍🏫',
    color: 'bg-yellow-100 text-yellow-800',
  },
  [FamilyInterestId.Tumbling]: {
    id: FamilyInterestId.Tumbling,
    name: 'Tumbling',
    emoji: '🤸',
    color: 'bg-pink-100 text-pink-800',
  },
  [FamilyInterestId.VideoGames]: {
    id: FamilyInterestId.VideoGames,
    name: 'Video Games',
    emoji: '🎮',
    color: 'bg-violet-100 text-violet-800',
  },
  [FamilyInterestId.WobblyLife]: {
    id: FamilyInterestId.WobblyLife,
    name: 'Wobbly Life',
    emoji: '🤪',
    color: 'bg-pink-100 text-pink-800',
  },
  [FamilyInterestId.Yoga]: {
    id: FamilyInterestId.Yoga,
    name: 'Yoga',
    emoji: '🧘',
    color: 'bg-rose-100 text-rose-800',
  },
};
